# Generated by Django 4.2.7 on 2024-02-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
